/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import ControladorBanco.ControladorBanco;
import Modelo.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author natam
 */
public class frmPrincipal2 extends javax.swing.JFrame {

    ControladorBanco banco;

    /**
     * Creates new form frmPrincipal2
     */
    public frmPrincipal2() {
        initComponents();
        setLocationRelativeTo(null);
        llenarCombox();
        banco = new ControladorBanco();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        tblAdministrarClientes = new javax.swing.JTabbedPane();
        panel2 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        lblDocumetoCliente = new javax.swing.JLabel();
        txtDocumentoCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        lblCorreoCliente = new javax.swing.JLabel();
        txtCorreoCliente = new javax.swing.JTextField();
        lblTelefonoCliente = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        btnCrearCliente = new javax.swing.JButton();
        btnBuscarCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        lblAnionNacimientoCliente = new javax.swing.JLabel();
        lblDiaNacimientoCliente = new javax.swing.JLabel();
        cbxDiaNacimientoCliente = new javax.swing.JComboBox<>();
        cbxMesNacimientoCliente = new javax.swing.JComboBox<>();
        lblAnioNacimientoCliente = new javax.swing.JLabel();
        cbxAñoNacimientoCliente = new javax.swing.JComboBox<>();
        lblEstaturaCliente = new javax.swing.JLabel();
        txtEstaturaCliente = new javax.swing.JTextField();
        lblTipoDeCliente = new javax.swing.JLabel();
        cbxTipoDeCliente = new javax.swing.JComboBox<>();
        lblMesNacimientoCliente = new javax.swing.JLabel();
        lblBancoUCaldas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        tblAdministrarClientes.addTab("Admin Cuentas", panel2);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Administrar clientes");

        lblDocumetoCliente.setText("Documento");

        txtDocumentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setText("Nombre");

        lblCorreoCliente.setText("Correo");

        txtCorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoClienteActionPerformed(evt);
            }
        });

        lblTelefonoCliente.setText("Telefono");

        txtTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoClienteActionPerformed(evt);
            }
        });

        btnCrearCliente.setText("Crear");
        btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearClienteActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");

        btnActualizarCliente.setText("Actualizar");

        btnEliminarCliente.setText("Eliminar");

        lblAnionNacimientoCliente.setText("Fecha de nacimiento");

        lblDiaNacimientoCliente.setText("Día");

        cbxDiaNacimientoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        lblAnioNacimientoCliente.setText("Año");

        lblEstaturaCliente.setText("Estatura");

        lblTipoDeCliente.setText("Tipo de cliente");

        cbxTipoDeCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persona Natural" }));

        lblMesNacimientoCliente.setText("Mes");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoDeCliente)
                            .addComponent(lblEstaturaCliente)
                            .addComponent(lblAnionNacimientoCliente))
                        .addGap(22, 22, 22)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTipoDeCliente, 0, 308, Short.MAX_VALUE)
                            .addComponent(txtEstaturaCliente)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDiaNacimientoCliente))
                                .addGap(72, 72, 72)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblMesNacimientoCliente)
                                    .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxAñoNacimientoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAnioNacimientoCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(184, 184, 184))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefonoCliente)
                                    .addComponent(lblCorreoCliente)
                                    .addComponent(lblNombreCliente)
                                    .addComponent(lblDocumetoCliente))
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                            .addComponent(txtCorreoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(120, 120, 120)))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearCliente)
                            .addComponent(btnBuscarCliente)
                            .addComponent(btnActualizarCliente)
                            .addComponent(btnEliminarCliente)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel3)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(49, 49, 49)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumetoCliente)
                    .addComponent(txtDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCliente)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearCliente))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoCliente)
                    .addComponent(txtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoCliente)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarCliente))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lblDiaNacimientoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnioNacimientoCliente)
                                    .addComponent(lblMesNacimientoCliente))
                                .addGap(15, 15, 15)))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnionNacimientoCliente)
                            .addComponent(cbxDiaNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMesNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxAñoNacimientoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstaturaCliente)
                            .addComponent(txtEstaturaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoDeCliente)
                            .addComponent(cbxTipoDeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tblAdministrarClientes.addTab("Admin Clientes", panel3);

        lblBancoUCaldas.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lblBancoUCaldas.setText("Banco U.Caldas");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblAdministrarClientes)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(lblBancoUCaldas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBancoUCaldas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblAdministrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblAdministrarClientes.getAccessibleContext().setAccessibleName("Administrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoClienteActionPerformed

    private void txtCorreoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoClienteActionPerformed

    private void txtTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoClienteActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        crearCliente();
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JComboBox<String> cbxAñoNacimientoCliente;
    private javax.swing.JComboBox<String> cbxDiaNacimientoCliente;
    private javax.swing.JComboBox<String> cbxMesNacimientoCliente;
    private javax.swing.JComboBox<String> cbxTipoDeCliente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnioNacimientoCliente;
    private javax.swing.JLabel lblAnionNacimientoCliente;
    private javax.swing.JLabel lblBancoUCaldas;
    private javax.swing.JLabel lblCorreoCliente;
    private javax.swing.JLabel lblDiaNacimientoCliente;
    private javax.swing.JLabel lblDocumetoCliente;
    private javax.swing.JLabel lblEstaturaCliente;
    private javax.swing.JLabel lblMesNacimientoCliente;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTelefonoCliente;
    private javax.swing.JLabel lblTipoDeCliente;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTabbedPane tblAdministrarClientes;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDocumentoCliente;
    private javax.swing.JTextField txtEstaturaCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables

    private void llenarCombox() {
        //Día de nacimiento
        for (int i = 31; i >= 1; i--) {
            cbxDiaNacimientoCliente.addItem(i + "");

        }
        //Mes de nacimiento
        for (int i = 12; i >= 1; i--) {
            cbxMesNacimientoCliente.addItem(i + "");
        }
        //Año de nacimiento
        for (int i = LocalDate.now().getYear(); i >= 2000; i--) {
            cbxAñoNacimientoCliente.addItem(i + "");
        }
    }

    private void crearCliente() {

        if (txtDocumentoCliente.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(this, "El documento es obligatorio");
        } else if (txtNombreCliente.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(this, "El nombre es obligatorio");
        } else if (txtCorreoCliente.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(this, "El correo es obligatorio");
        } else if (txtTelefonoCliente.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(this, "El telefono es obligatorio");
        } else if (txtEstaturaCliente.getText().equals("")) {
            JOptionPane.showInternalMessageDialog(this, "La estatura es obligatorio");
        } else {

            String tipo = cbxTipoDeCliente.getSelectedItem().toString();
            String documento = txtDocumentoCliente.getText();
            String nombre = txtNombreCliente.getText();
            String correo = txtCorreoCliente.getText();
            String telefono = txtTelefonoCliente.getText();
            int diaDeNacimiento = Integer.parseInt(cbxDiaNacimientoCliente.getSelectedItem().toString());
            int mesDeNacimineto = Integer.parseInt(cbxMesNacimientoCliente.getSelectedItem().toString());
            int anioDeNacimiento = Integer.parseInt(cbxAñoNacimientoCliente.getSelectedItem().toString());
            double estatura = Double.parseDouble(txtEstaturaCliente.getText());

            Cliente cliente = banco.crearCliente(tipo, documento, nombre, correo, telefono, ICONIFIED, ICONIFIED, ICONIFIED, ERROR);
            if (cliente != null) {
                JOptionPane.showInternalMessageDialog(this, "Cliente creado correctamente...");
                System.out.println(cliente.getDocumento() + " - " + cliente.getNombre());
            } else {
                JOptionPane.showInternalMessageDialog(this, "Error al crear el cliente...");
            }
        }

    }
}
